export const EXPIRATION_CONSTANTS = {
 
  RESERVATION_EXPIRY_MINUTES: 2,
  RESERVATION_EXPIRY_MS: 2 * 60 * 1000, 
  RESERVATION_EXPIRY_SECONDS: 2 * 60,   

  CLEANUP_INTERVAL_SECONDS: 30,
  CLEANUP_CRON: '*/30 * * * * *',

  IDEMPOTENCY_TTL_SECONDS: 86400,

  LOCK_TTL_SECONDS: 10,

  MAX_RETRY_ATTEMPTS: 3,
  RETRY_DELAY_MS: 100,
};